FROM ruby:2.4

WORKDIR /usr/src/app
COPY Gemfile ./
COPY Gemfile.lock ./

RUN gem install bundler

COPY . .

RUN bundle install

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "webrick", "-e", "production", "-b", "0.0.0.0"]